---
#
# Uninstall Couchbase cluster from a single command
#
- name: Couchbase Installation
  hosts: all
  sudo: true

  tasks:
  - name: Uninstall Couchbase
    shell: dpkg -r couchbase-server
  - name: Delete files (just to have a fresh install)
    file: path=/opt/couchbase/ state=absent



